# https://taskfile.dev

version: '3'

tasks:
  console:
    cmds:
      - docker exec -it sql_parse /bin/bash
  build:
    cmds:
      - docker compose build
  up:
    cmds:
      - docker compose up -d
